# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedMadRobotTestTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedMadRobotTestTask

  pod 'SwiftLint'
  pod 'R.swift'

  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'

end
