# platform :ios, '13.0'

target 'RedMadRobotTestTask' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'R.swift'

end

target 'RedMadRobotTestTaskAPI' do
  use_frameworks!

  pod 'Apexy'

  target 'RedMadRobotTestTaskTests' do
    inherit! :search_paths
  end

  target 'RedMadRobotTestTaskAPITests' do
    inherit! :search_paths
  end

end